apiVersion: v1 
kind: Pod 
metadata:
  name: my-pod-configmap-secret
  namespace: default
  labels:
    app: my-app
spec:
  containers:
  - name: my-container
    image: busybox
    command: ["/bin/sh","-c","env"]
    env:
      - name: MY_VAR_02 
        valueFrom:
          configMapKeyRef:
            name: my-configmap
            key: my_env_var02
  restartPolicy: Never

